#!/usr/bin/env python3
"""Interactive jellyGPT installer/config wizard.

This script is intentionally dependency-light so users can run it before installing
Python packages. It writes a .env file and a docker-compose.local.yml file, then
prints the next commands to run.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"
COMPOSE_PATH = ROOT / "docker-compose.local.yml"

COMMON_JELLYFIN_DATA_PATHS = [
    "/var/lib/jellyfin/data",
    "/config/data",
    "/srv/jellyfin/data",
    "/opt/jellyfin/data",
]


def ask(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or (default or "")


def ask_bool(prompt: str, default: bool = False) -> bool:
    default_text = "Y/n" if default else "y/N"
    while True:
        value = input(f"{prompt} [{default_text}]: ").strip().lower()
        if not value:
            return default
        if value in {"y", "yes", "true", "1"}:
            return True
        if value in {"n", "no", "false", "0"}:
            return False
        print("Please answer y or n.")


def find_existing_data_path() -> str:
    for path in COMMON_JELLYFIN_DATA_PATHS:
        p = Path(path)
        if (p / "jellyfin.db").exists() or (p / "playback_reporting.db").exists():
            return path
    return "/var/lib/jellyfin/data"


def safe_service_name(value: str) -> str:
    value = value.strip().lower() or "jellygpt"
    value = re.sub(r"[^a-z0-9_.-]+", "-", value)
    return value.strip("-._") or "jellygpt"


def command_exists(command: str) -> bool:
    return shutil.which(command) is not None


def docker_compose_command() -> list[str] | None:
    if not command_exists("docker"):
        return None
    try:
        subprocess.run(["docker", "compose", "version"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return ["docker", "compose"]
    except Exception:
        pass
    if command_exists("docker-compose"):
        return ["docker-compose"]
    return None


def write_env(config: dict[str, str]) -> None:
    lines = [
        "# Generated by jellyGPT install.py",
        "# Review before sharing. This file may contain secrets.",
        "",
    ]
    for key, value in config.items():
        escaped = value.replace('"', '\\"')
        lines.append(f'{key}="{escaped}"')
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_compose(config: dict[str, str], include_ollama: bool, service_name: str, enable_profile: bool = False) -> None:
    data_path = config["HOST_JELLYFIN_DATA_PATH"]
    image = config.get("JELLYGPT_IMAGE", "ghcr.io/YOUR_GITHUB_USER_OR_ORG/jellygpt:latest")
    lines = [
        "# Generated by jellyGPT install.py",
        "services:",
        f"  {service_name}:",
        f"    image: {image}",
        "    ports:",
        "      - \"8787:8787\"",
        "    env_file:",
        "      - .env",
        "    volumes:",
        f"      - {data_path}:/jellyfin-data:ro",
        "      - jellygpt-cache:/cache",
        "    restart: unless-stopped",
    ]
    if include_ollama:
        lines += [
            "    depends_on:",
            "      - ollama",
        ]
    if enable_profile:
        lines += [
            "",
            f"  {service_name}-profile-worker:",
            f"    image: {image}",
            "    command: [\"jellygpt\", \"worker\", \"profile-loop\"]",
            "    env_file:",
            "      - .env",
            "    volumes:",
            f"      - {data_path}:/jellyfin-data:ro",
            "      - jellygpt-cache:/cache",
            "    restart: unless-stopped",
        ]
        if include_ollama:
            lines += [
                "    depends_on:",
                "      - ollama",
            ]
    if include_ollama:
        lines += [
            "",
            "  ollama:",
            "    image: ollama/ollama:latest",
            "    ports:",
            "      - \"11434:11434\"",
            "    volumes:",
            "      - ollama:/root/.ollama",
            "    restart: unless-stopped",
        ]
    lines += [
        "",
        "volumes:",
        "  jellygpt-cache:",
    ]
    if include_ollama:
        lines.append("  ollama:")
    COMPOSE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    print("\n🪼 jellyGPT installer")
    print("This wizard creates .env and docker-compose.local.yml for self-hosting.\n")

    if ENV_PATH.exists() and not ask_bool(".env already exists. Overwrite it?", False):
        print("Aborted without changing .env.")
        return 1

    jellyfin_url = ask("Jellyfin URL", "http://jellyfin:8096")
    api_key = ask("Jellyfin API key (leave blank to fill later)", "")
    default_data_path = find_existing_data_path()
    data_path = ask("Host path to Jellyfin data directory", default_data_path)
    playback_db_name = ask("Playback Reporting DB filename", "playback_reporting.db")
    jellyfin_db_name = ask("Jellyfin DB filename", "jellyfin.db")
    refresh = ask("Recommendation refresh interval", "30m")
    default_algo = ask("Default recommendation algorithm", "blended")

    enable_llm = ask_bool("Enable optional Ollama AI reranking?", False)
    enable_profile = ask_bool("Enable periodic AI taste-profile Markdown updates?", False)
    ollama_url = ask("Ollama URL", "http://ollama:11434") if (enable_llm or enable_profile) else "http://ollama:11434"
    ollama_model = ask("Ollama model", "llama3.2:3b") if (enable_llm or enable_profile) else "llama3.2:3b"
    include_ollama = (enable_llm or enable_profile) and ask_bool("Include an Ollama service in docker-compose.local.yml?", True)

    service_name = safe_service_name(ask("Docker Compose service name", "jellygpt"))

    config = {
        "JELLYFIN_URL": jellyfin_url,
        "JELLYFIN_API_KEY": api_key,
        "HOST_JELLYFIN_DATA_PATH": data_path,
        "PLAYBACK_DB": f"/jellyfin-data/{playback_db_name}",
        "JELLYFIN_DB": f"/jellyfin-data/{jellyfin_db_name}",
        "CACHE_DIR": "/cache",
        "RECS_REFRESH_INTERVAL": refresh,
        "RECS_DEFAULT_ALGO": default_algo,
        "RECS_ALGOS": "existing_logic_like,recency_popularity,label_profile,blended,llm_rerank",
        "ENABLE_LLM_RERANK": "true" if enable_llm else "false",
        "ENABLE_LLM_LABELING": "false",
        "ENABLE_PROFILE_UPDATES": "true" if enable_profile else "false",
        "TASTE_PROFILE_PATH": "/cache/profiles/default.md",
        "PROFILE_REFRESH_INTERVAL_SECONDS": "3600",
        "PROFILE_CHUNK_EVENTS": "50",
        "PROFILE_MAX_EVENTS_PER_RUN": "1000",
        "PROFILE_REQUIRE_OLLAMA": "true" if enable_profile else "false",
        "OLLAMA_URL": ollama_url,
        "OLLAMA_MODEL": ollama_model,
        "JELLYGPT_IMAGE": "ghcr.io/YOUR_GITHUB_USER_OR_ORG/jellygpt:latest",
    }

    write_env(config)
    write_compose(config, include_ollama=include_ollama, service_name=service_name, enable_profile=enable_profile)

    print("\nCreated:")
    print(f"  {ENV_PATH}")
    print(f"  {COMPOSE_PATH}")

    compose = docker_compose_command()
    compose_text = " ".join(compose) if compose else "docker compose"
    print("\nNext steps:")
    print(f"  1. Review {ENV_PATH.name}")
    if not api_key:
        print("  2. Add JELLYFIN_API_KEY to .env")
        step = 3
    else:
        step = 2
    print(f"  {step}. Start jellyGPT:")
    print(f"     {compose_text} -f docker-compose.local.yml up -d")
    print(f"  {step + 1}. Check health:")
    print("     curl http://localhost:8787/health")
    print(f"  {step + 2}. Configure JellyTube with:")
    print("     JELLYGPT_URL=http://jellygpt:8787")

    if enable_llm and include_ollama:
        print("\nOptional model pull after Ollama starts:")
        print(f"  {compose_text} -f docker-compose.local.yml exec ollama ollama pull {ollama_model}")

    print("\nDone. jellyGPT should remain optional; JellyTube can still fall back if this service is down.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
